-- -----------------------------------------------------
-- Add sample data to index_server relation
--author: Pablo Caruana
--email: pablo dot caruana at gmail dot com
--date: 12/1/2016
-- -----------------------------------------------------
